//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS.DAL.DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class getallorderuser
    {
        public string invoiceId { get; set; }
        public int id { get; set; }
        public string user { get; set; }
        public decimal bill { get; set; }
        public string payment { get; set; }
        public System.DateTime invoicedate { get; set; }
    }
}
