//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS.DAL.DatabaseContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class getallorder
    {
        public string cfullname { get; set; }
        public int user { get; set; }
        public string pro_name { get; set; }
        public string cpno { get; set; }
        public string caddress { get; set; }
        public decimal oprice { get; set; }
        public int oqty { get; set; }
        public decimal oamount { get; set; }
        public Nullable<System.DateTime> odate { get; set; }
        public string cemail { get; set; }
    }
}
