//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS.DAL.DatabaseContext
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class regcustomer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public regcustomer()
        {
            this.invoicetables = new HashSet<invoicetable>();
            this.ordertables = new HashSet<ordertable>();
        }
    
        public int id { get; set; }
        [Required]
        public string cfullname { get; set; }
        [Required]
        public string caddress { get; set; }
        [Required]
       
        public string cpno { get; set; }
        [Required]

        public string cemail { get; set; }
        [Required]
       
        public string cpassword { get; set; }
        public string cphoto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<invoicetable> invoicetables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ordertable> ordertables { get; set; }
    }
}
