//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS.DAL.DatabaseContext
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class regcustomer
    {
        public int id { get; set; }
        [Required]
        public string cfullname { get; set; }
        [Required]
        public string caddress { get; set; }
        [Required]
        [Range(10,14,ErrorMessage ="please enter number between 8 to 12")]
        public string cpno { get; set; }
        [Required]
        [RegularExpression("/^([A-Za-z0-9_./])+@([A-Za-z0-9_.])+.([A-Za-z]{2,4})$/;",ErrorMessage ="please enter the correct format")]
        public string cemail { get; set; }
        [Required]
        [Range(8, 14, ErrorMessage = "please enter number between 8 to 12")]
        public string cpassword { get; set; }
    }
}
