//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS.DAL.DatabaseContext
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class regcustomer
    {
       
        public int id { get; set; }

        [Required(ErrorMessage = "This field is Required")]
        [Display(Name ="cfullname")]
    
        public string cfullname { get; set; }
        public string caddress { get; set; }
        public string cpno { get; set; }
        public string cemail { get; set; }
        public string cpassword { get; set; }
    }
}
